<?php

use Illuminate\Database\Seeder;

class JedloTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("jedlo")->insert(array(
            array(
                "typ"   => "normal",
                "popis" => "Rezeň so zemiakovou kašou",
                "cena"  => 150.00,
                "dostupnost"=> "ano",
                "hmotnost" => 350,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 1,
                "obrazok" => "rezen.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepková pizza",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 1,
                "obrazok" => "pizza.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 1,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 1,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 1,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Grécky šalát",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 1,
                 "obrazok" => "grecky.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Rezeň so zemiakovou kašou",
                "cena"  => 200.00,
                "dostupnost"=> "ano",
                "hmotnost" => 450,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 2,
                "obrazok" => "rezen.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Špeciálne bezlepkové cestoviny",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 2,
                "obrazok" => "cestoviny.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 2,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 2,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 2,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Grécky šalát",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 2,
                "obrazok" => "grecky.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Rezeň so zemiakovou kašou",
                "cena"  => 150.00,
                "dostupnost"=> "ano",
                "hmotnost" => 350,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 3,
                 "obrazok" => "rezen.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Špeciálne bezlepkové cestoviny",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 3,
                "obrazok" => "cestoviny.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 3,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 3,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 3,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Grécky šalát",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 3,
                "obrazok" => "grecky.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Rezeň so zemiakovou kašou",
                "cena"  => 150.00,
                "dostupnost"=> "ano",
                "hmotnost" => 350,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 4,
                "obrazok" => "rezen.jpg",

            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Špeciálne bezlepkové cestoviny",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 4,
                "obrazok" => "cestoviny.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 4,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 4,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 4,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Ceasar šalát s krutónmi",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 4,
                "obrazok" => "caesa.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Losos s zeleninovým šalátom",
                "cena"  => 150.00,
                "dostupnost"=> "ano",
                "hmotnost" => 350,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 5,
                 "obrazok" => "loso.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Špeciálne bezlepkové cestoviny",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 5,
                "obrazok" => "cestoviny.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 5,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 5,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 5,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Ceasar šalát s krutónmi",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 5,
                "obrazok" => "caesa.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Losos s zeleninovým šalátom",
                "cena"  => 150.00,
                "dostupnost"=> "ano",
                "hmotnost" => 350,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 6,
                "obrazok" => "loso.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Špeciálne bezlepkové cestoviny",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 6,
                "obrazok" => "cestoviny.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 6,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 6,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "nie",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 6,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Ceasar šalát s krutónmi",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 6,
                "obrazok" => "caesa.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Rezeň so zemiakovou kašou",
                "cena"  => 150.00,
                "dostupnost"=> "ano",
                "hmotnost" => 350,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 7,
                "obrazok" => "rezen.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepková pizza",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 3,
                "obrazok" => "pizza.jpg",
            ),
            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepková pizza",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 7,
                "obrazok" => "pizza.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Zeleninový wrap",
                "cena"  => 180.00,
                "dostupnost"=> "ano",
                "hmotnost" => 280,
                "kategoria" => "hlavne",
                "id_stala_ponuka" => 7,
                "obrazok" => "wrap.jpg",
            ),
            array(
                "typ"   => "vegetarian",
                "popis" => "Zapečená brokolica so zemiakmi",
                "cena"  => 100.00,
                "dostupnost"=> "ano",
                "hmotnost" => 200,
                "kategoria" => "predjedlo",
                "id_stala_ponuka" => 7,
                "obrazok" => "brokolica.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Čokoládový raw koláčik",
                "cena"  => 69.00,
                "dostupnost"=> "nie",
                "hmotnost" => 100,
                "kategoria" => "dezert",
                "id_stala_ponuka" => 7,
                "obrazok" => "kolac.jpg",
            ),
            array(
                "typ"   => "fit",
                "popis" => "Grécky šalát",
                "cena"  => 120.00,
                "dostupnost"=> "ano",
                "hmotnost" => 250,
                "kategoria" => "salat",
                "id_stala_ponuka" => 7,
                "obrazok" => "grecky.jpg",
            ),

        ));
    }
}
