<?php

use Illuminate\Database\Seeder;

class NapojTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("napoj")->insert(array(
            array(
                "typ"   => "normal",
                "popis" => "Malinová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 1,
                "obrazok" => "limonada.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 1,
                "obrazok" => "pivo.jpg",
            ),

            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 1,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 1,
                "obrazok" => "kokos.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 1,
                "obrazok" => "turek.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 1,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Citrónová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 2,
                "obrazok" => "citron.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 2,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 2,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 2,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Malinová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 2,
                "obrazok" => "limonada.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 2,
                "obrazok" => "kokos.jpg",
            ),

            array(
                "typ"   => "normal",
                "popis" => "Ríbezľové víno",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 200,
                "kategoria" => "vino",
                "id_stala_ponuka" => 2,
                "obrazok" => "vino.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Pšeničné pivo",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 2,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 2,
                "obrazok" => "turek.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Citrónová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 3,
                "obrazok" => "citron.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 3,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 3,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 3,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 3,
                "obrazok" => "kokos.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 3,
                "obrazok" => "turek.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ríbezľové víno",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 200,
                "kategoria" => "vino",
                "id_stala_ponuka" => 3,
                "obrazok" => "vino.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Pšeničné pivo",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 3,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Citrónová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 4,
                "obrazok" => "citron.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 4,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 4,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 4,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 4,
                "obrazok" => "kokos.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 4,
                "obrazok" => "turek.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ríbezľové víno",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 200,
                "kategoria" => "vino",
                "id_stala_ponuka" => 4,
                "obrazok" => "vino.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Pšeničné pivo",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 4,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Citrónová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 5,
                "obrazok" => "citron.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 5,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 5,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 5,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ríbezľové víno",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 200,
                "kategoria" => "vino",
                "id_stala_ponuka" => 5,
                "obrazok" => "vino.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 5,
                "obrazok" => "kokos.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 5,
                "obrazok" => "turek.jpg",
            ),

            array(
                "typ"   => "normal",
                "popis" => "Pšeničné pivo",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 5,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Citrónová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 6,
                "obrazok" => "citron.jpg",
            ),

            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 6,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 6,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 6,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 6,
                "obrazok" => "kokos.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 6,
                "obrazok" => "turek.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ríbezľové víno",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 200,
                "kategoria" => "vino",
                "id_stala_ponuka" => 6,
                "obrazok" => "vino.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Malinová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 6,
                "obrazok" => "limonada.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Pšeničné pivo",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 6,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Citrónová limonáda",
                "cena"  => 39.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "limonady",
                "id_stala_ponuka" => 7,
                "obrazok" => "citron.jpg",
            ),


            array(
                "typ"   => "vegan",
                "popis" => "Latte z mandľového mlieka",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 7,
                "obrazok" => "latte.jpeg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ovocný čaj",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "čaj",
                "id_stala_ponuka" => 7,
                "obrazok" => "caj.jpg",
            ),
            array(
                "typ"   => "bezlepok",
                "popis" => "Bezlepkové pivo",
                "cena"  => 50.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 7,
                "obrazok" => "pivo.jpg",
            ),
            array(
                "typ"   => "raw",
                "popis" => "Raw kokosový nápoj",
                "cena"  => 69.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "drink",
                "id_stala_ponuka" => 7,
                "obrazok" => "kokos.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Zalievaná takzvaná turecká káva",
                "cena"  => 29.00,
                "dostupnost"=> "ano",
                "objem" => 330,
                "kategoria" => "kava",
                "id_stala_ponuka" => 7,
                "obrazok" => "turek.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Ríbezľové víno",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 200,
                "kategoria" => "vino",
                "id_stala_ponuka" => 7,
                "obrazok" => "vino.jpg",
            ),
            array(
                "typ"   => "normal",
                "popis" => "Pšeničné pivo",
                "cena"  => 45.00,
                "dostupnost"=> "ano",
                "objem" => 500,
                "kategoria" => "pivo",
                "id_stala_ponuka" => 7,
                "obrazok" => "pivo.jpg",
            ),
        ));
    }
}
